#cloud-config

# Above line is not a comment, it is required for cloud-config to run, it is similar to a shebang line in bash!

# Run all the config commands
runcmd:
# Make testfile to see cloud-init started
  - sudo touch /home/ubuntu/test.txt
# Update apt packages
  - sudo apt-get update
# Install all dependencies
  - sudo apt install -y apache2
  - cd /var/www
  - sudo echo "hello terraform Apache" >> index.html
  - sudo cp index.html html/index.html
  # - cd /etc/apache2
  # - sudo sed -i 's/80/42069/' ports.conf
  - sudo systemctl reload apache2
# Create file to denote script run is finished
  - sudo touch /home/ubuntu/apache_ready.csv